using UnityEngine;
using UnityEditor;
using System.Collections.Generic;

public class RenameCountries : EditorWindow
{
    [MenuItem("Tools/Rename Countries to English")]
    static void Rename()
    {
        // 找到场景中的 EarthCountries 节点
        GameObject earthCountries = GameObject.Find("Earth/EarthCountries");
        if (earthCountries == null)
        {
            Debug.LogError("❌ 找不到 EarthCountries 对象！");
            return;
        }

        // 映射表（俄语 -> 英语）
        Dictionary<string, string> nameMap = new Dictionary<string, string>()
{
    {"Abkhazia", "Abkhazia"},
    {"Afghanistan", "Afghanistan"},
    {"Albania", "Albania"},
    {"Algeria", "Algeria"},
    {"United States", "United States"},
    {"Angola", "Angola"},
    {"Antarctica", "Antarctica"},
    {"Argentina", "Argentina"},
    {"Armenia", "Armenia"},
    {"Avstralia", "Australia"},
    {"Austria", "Austria"},
    {"Azerbaidjan", "Azerbaijan"},
    {"Bahamas", "Bahamas"},
    {"Bangladesh", "Bangladesh"},
    {"Barbados", "Barbados"},
    {"Belarus", "Belarus"},
    {"Belgium", "Belgium"},
    {"Belize", "Belize"},
    {"Benin", "Benin"},
    {"Bolgariya", "Bulgaria"},
    {"Bolivia", "Bolivia"},
    {"Bosnia and Herzegovina", "Bosnia and Herzegovina"},
    {"Botswana", "Botswana"},
    {"Brazil", "Brazil"},
    {"United Kingdom", "United Kingdom"},
    {"Brunei", "Brunei"},
    {"Burundi", "Burundi"},
    {"Burkina Faso", "Burkina Faso"},
    {"Butan", "Bhutan"},
    {"Camerun", "Cameroon"},
    {"Canada", "Canada"},
    {"CentrAfrRespub", "Central African Republic"},
    {"Chad", "Chad"},
    {"Chehiya", "Czech Republic"},
    {"Chernogoriya", "Montenegro"},
    {"Chili", "Chile"},
    {"Columbiya", "Colombia"},
    {"Daniya", "Denmark"},
    {"DemocrRespKongo", "Democratic Republic of the Congo"},
    {"Djibuti", "Djibouti"},
    {"Dominika", "Dominica"},
    {"DominikanskResp", "Dominican Republic"},
    {"EcvatorGvineya", "Equatorial Guinea"},
    {"Efiopia", "Ethiopia"},
    {"Egipet", "Egypt"},
    {"Ekvador", "Ecuador"},
    {"Eritreya", "Eritrea"},
    {"Estoniya", "Estonia"},
    {"Fidji", "Fiji"},
    {"Filipiny", "Philippines"},
    {"Finlyandia", "Finland"},
    {"FolklendskieOstrova", "Falkland Islands"},
    {"Franciya", "France"},
    {"Gabon", "Gabon"},
    {"Gaina", "Guyana"},
    {"Gaiti", "Haiti"},
    {"Gambiya", "Gambia"},
    {"Gana", "Ghana"},
    {"Germaniya", "Germany"},
    {"Gonduras", "Honduras"},
    {"Greciya", "Greece"},
    {"Grusiya", "Georgia"},
    {"Gvatemala", "Guatemala"},
    {"Gvineya", "Guinea"},
    {"GvineyaBisau", "Guinea-Bissau"},
    {"Harvatiya", "Croatia"},
    {"Iemen", "Yemen"},
    {"India", "India"},
    {"Indonesia", "Indonesia"},
    {"Iordaniya", "Jordan"},
    {"Irak", "Iraq"},
    {"Iran", "Iran"},
    {"Irlandiya", "Ireland"},
    {"Islandiya", "Iceland"},
    {"Ispaniya", "Spain"},
    {"Israel", "Israel"},
    {"Italiya", "Italy"},
    {"Japan", "Japan"},
    {"KabaVerde", "Cape Verde"},
    {"Kambodja", "Cambodia"},
    {"Katar", "Qatar"},
    {"Kazahstan", "Kazakhstan"},
    {"Kenia", "Kenya"},
    {"Kipr", "Cyprus"},
    {"Kirgistan", "Kyrgyzstan"},
    {"Kitai", "China"},
    {"Kodivuar", "Ivory Coast"},
    {"Kongo", "Republic of the Congo"},
    {"KostaRika", "Costa Rica"},
    {"Kuba", "Cuba"},
    {"Kuveit", "Kuwait"},
    {"Laos", "Laos"},
    {"Latviya", "Latvia"},
    {"Lesoto", "Lesotho"},
    {"Liberiya", "Liberia"},
    {"Litva", "Lithuania"},
    {"Livan", "Lebanon"},
    {"Liviya", "Libya"},
    {"Luxemburg", "Luxembourg"},
    {"Madagaskar", "Madagascar"},
    {"Makedoniya", "North Macedonia"},
    {"Malaisia", "Malaysia"},
    {"Malavi", "Malawi"},
    {"Mali", "Mali"},
    {"Malta", "Malta"},
    {"Marokko", "Morocco"},
    {"Martinika", "Martinique"},
    {"Mavrikii", "Mauritius"},
    {"Mavritaniya", "Mauritania"},
    {"Mexika", "Mexico"},
    {"Moldova", "Moldova"},
    {"Mongoliya", "Mongolia"},
    {"Mozambik", "Mozambique"},
    {"Myanma", "Myanmar"},
    {"Namibia", "Namibia"},
    {"Nepal", "Nepal"},
    {"Neytral", "Neutral Zone (Saudi-Kuwait)"},
    {"Neytral_2", "Neutral Zone 2"},
    {"Nidelnady", "Netherlands"},
    {"Niger", "Niger"},
    {"Nigeriya", "Nigeria"},
    {"Nikaragua", "Nicaragua"},
    {"Norvegiya", "Norway"},
    {"NovayaKaledonia", "New Caledonia"},
    {"NovayaZelandia", "New Zealand"},
    {"OAE", "United Arab Emirates"},
    {"Oman", "Oman"},
    {"Pakistan", "Pakistan"},
    {"Panama", "Panama"},
    {"PapuaNovayaGvinea", "Papua New Guinea"},
    {"Paragvai", "Paraguay"},
    {"Peru", "Peru"},
    {"Polsha", "Poland"},
    {"Portugaliya", "Portugal"},
    {"PuertoRiko", "Puerto Rico"},
    {"Reynion", "Réunion"},
    {"Rossia", "Russia"},
    {"Ruanda", "Rwanda"},
    {"Ruminiya", "Romania"},
    {"Salvador", "El Salvador"},
    {"Samoa", "Samoa"},
    {"SaudovskayaAraviya", "Saudi Arabia"},
    {"Senegal", "Senegal"},
    {"Serbiya", "Serbia"},
    {"SevernKoreya", "North Korea"},
    {"ShriLanka", "Sri Lanka"},
    {"SieraLione", "Sierra Leone"},
    {"Siriya", "Syria"},
    {"Slovakiya", "Slovakia"},
    {"Sloveniya", "Slovenia"},
    {"SolomonOstrova", "Solomon Islands"},
    {"Somali", "Somalia"},
    {"Sudan", "Sudan"},
    {"Surinam", "Suriname"},
    {"Svazilend", "Eswatini"},
    {"Sweciya", "Sweden"},
    {"Sweizariya", "Switzerland"},
    {"Tadjikistan", "Tajikistan"},
    {"Tailand", "Thailand"},
    {"Taiwan", "Taiwan"},
    {"Tanzania", "Tanzania"},
    {"Togo", "Togo"},
    {"TrinidadTobago", "Trinidad and Tobago"},
    {"Tunis", "Tunisia"},
    {"Turciya", "Turkey"},
    {"Turkmenistan", "Turkmenistan"},
    {"UAR", "Egypt (UAR)"},
    {"Uganda", "Uganda"},
    {"Ukraina", "Ukraine"},
    {"Urugvai", "Uruguay"},
    {"Uzbekistan", "Uzbekistan"},
    {"UznayaKoreya", "South Korea"},
    {"UznDjordjia", "South Georgia and the South Sandwich Islands"},
    {"Vanuatu", "Vanuatu"},
    {"Venesuela", "Venezuela"},
    {"Vengriya", "Hungary"},
    {"Vietnam", "Vietnam"},
    {"Yamaika", "Jamaica"},
    {"YuzniySudan", "South Sudan"},
    {"Zambiya", "Zambia"},
    {"Zimbabve", "Zimbabwe"}
};

        int changed = 0;
        foreach (Transform child in earthCountries.transform)
        {
            if (nameMap.TryGetValue(child.name, out string newName))
            {
                child.name = newName;
                changed++;
            }
        }

        Debug.Log($"✅ 重命名完成：共修改 {changed} 个国家。");
    }
}
